server:
    error:
        include-stacktrace: never

spring:
    datasource:
        url: dbc:postgresql://localhost:5432/user?useSSl=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: postgresql
        password: joao
    jpa:
        ddl-auto: update